### ISSUE TITLE
Error when running npm start

### ISSUE THREAD

**Issue by hermstadalex** [super-urban-people/coffeehouse#1]
I get this error when I run npm start after installing. Any ideas? 

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/alexanderhermstad/workspace/coding_projects/ethereum-boilerplate/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.6.0
```

**Comment by samkohli** [comment]
NODE_OPTIONS=--openssl-legacy-provider yarn run start

**Comment by hermstadalex** [comment]
> NODE_OPTIONS=--openssl-legacy-provider yarn run start

Where to put this?
